### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'append'

### ISSUE THREAD

**Issue by peterjschroeder** [agarden/remove-pdf-watermark#1]
When run with parameters, the program errors out on line 33.

**Comment by agarden** [comment]
Just pushed a fix for the code around line 33. I do not know that it will solve your problem. If it doesn't, post a screenshot of the error. Thanks!

**Comment by peterjschroeder** [comment]
Thank you. Error is gone. Although new problem, doesn't seem to remove anything. Maybe a problem with watermark text having spaces? I put in in " and '

**Comment by agarden** [comment]
Could be. Use pdftk to uncompress the file and then open it in a text
editor and search.

pdftk <filename> output temp.pdf uncompress

I have only tested this script on a few PDFs that I needed to remove a
watermark on. There are probably a myriad of other ways that the watermark
might be inserted in the PDF which the script would fail to remove. If each
letter were a separate PDF object, for example, instead of the whole string
being a single object, then it wouldn't find it. You could try running the
program removing just a single letter at a time and see if that works.
